title: Umer Huzaifa, PhD
logo: /assets/images/profile_huzaifa.png
description: #Umer Huzaifa's personal website.
show_downloads: false
# google_analytics: 
theme: jekyll-theme-minimal

# Add this to _config.yml
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact