title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

# Add this to _config.yml
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact