################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1


################ French language ##################
[fr]
languageName = "French"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
